# Generated by Django 5.2 on 2025-05-06 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eser',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='eser_resimleri/'),
        ),
        migrations.AlterField(
            model_name='sanatci',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='sanatci_resimleri/'),
        ),
        migrations.CreateModel(
            name='EserResim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.ImageField(upload_to='eser_resimleri_ek/')),
                ('eser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resimler', to='core.eser')),
            ],
        ),
        migrations.CreateModel(
            name='SanatciResim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.ImageField(upload_to='sanatci_resimleri_ek/')),
                ('sanatci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resimler', to='core.sanatci')),
            ],
        ),
    ]
