# Generated by Django 5.2 on 2025-05-06 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_eser_resim_alter_sanatci_resim_eserresim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eserresim',
            name='eser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ek_resimler', to='core.eser'),
        ),
        migrations.AlterField(
            model_name='sanatciresim',
            name='sanatci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ek_resimler', to='core.sanatci'),
        ),
    ]
