# Generated by Django 5.2 on 2025-05-08 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_eserresim_eser_alter_sanatciresim_sanatci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eser',
            name='sanatci',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sanatci'),
        ),
        migrations.CreateModel(
            name='MuzeResim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.ImageField(upload_to='muze_resimleri_ek/')),
                ('muze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ek_resimler', to='core.muze')),
            ],
        ),
    ]
