# Generated by Django 5.2 on 2025-05-08 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_eser_sanatci_muzeresim'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MuzeResim',
        ),
    ]
